### ISSUE TITLE
problem with stand along version after building in anaconda

### ISSUE THREAD

**Issue by speranzaee** [niaid/imaris_extensions#48]
We have tried to build the imaris environment using anaconda on windows. The build goes without issues and the extension window will pop up. However, when we try to select the drop down menu, the following error comes up. 

QWindowsWindow::setMouseGrabEnabled: Not setting mouse grab for invisible window QWidgetWindow/'QMenuClassWindow'

**Comment by zivy** [comment]
Hello @speranzaee,

I tried reproducing this issue on a windows machine, assuming that is what you used, and wasn't able to replicate.

Please try the following (going around anaconda, as I am guessing that is the problem):

0. Open miniconda/anaconda base environment terminal/prompt.
1. Remove the existing imaris anaconda environment:
```
conda remove -n imaris --all
```
2. Create a new "empty" environment and activate it:
```
conda create -n imaris python=3.7.0
conda activate imaris
```
3. Update pip and install all packages from PyPi (assumes you changed directory to where the requirements.txt file is located, the imaris extensions directory):
```
 python -m pip install --upgrade pip
 python -m pip install -r requirements.txt
```
4. Try running the extensions.
