### ISSUE TITLE
Installing and using Channel Arithmetic in Imaris

### ISSUE THREAD

**Issue by Noush-A** [niaid/imaris_extensions#74]
Hi there,
I have a very naïve question here. I am trying to set up imaris_extensions (particularly interested in channel Arithmetic). I have followed the steps mentioned in the set up guide; installed Python 3.7, created the environment, configure imaris to point to python executable and the directory including the extensions. When I attempt to run 'run_extensions.bat', I receive the following code. When I press a key, it just closes the command prompt. I am not sure what I am doing wrong or not doing at all. I would appreciate any help in setting up this extension.  

Thank you and sorry about the basic question.

C:\Program Files\Bitplane\Imaris 10.1.1\XT\python3\imaris_extensions-main>REM Provide the full path to the activate batch script.

C:\Program Files\Bitplane\Imaris 10.1.1\XT\python3\imaris_extensions-main>REM Path is in quotation marks to accommodate for spaces in

C:\Program Files\Bitplane\Imaris 10.1.1\XT\python3\imaris_extensions-main>REM directory names.

C:\Program Files\Bitplane\Imaris 10.1.1\XT\python3\imaris_extensions-main>REM Need to use 'call' because this is a batch file invoked

C:\Program Files\Bitplane\Imaris 10.1.1\XT\python3\imaris_extensions-main>REM from this batch file. Need to activate explicitly as this

C:\Program Files\Bitplane\Imaris 10.1.1\XT\python3\imaris_extensions-main>REM places the appropriate DLLs in the path.

C:\Program Files\Bitplane\Imaris 10.1.1\XT\python3\imaris_extensions-main>call "F:\toolkits\Anaconda3\Scripts\activate" imaris
'"F:\toolkits\Anaconda3\Scripts\activate"' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Bitplane\Imaris 10.1.1\XT\python3\imaris_extensions-main>python ExtensionDriver.py
Traceback (most recent call last):
  File "ExtensionDriver.py", line 25, in <module>
    from PySide6.QtWidgets import QApplication, QLabel, QMainWindow
ModuleNotFoundError: No module named 'PySide6'

C:\Program Files\Bitplane\Imaris 10.1.1\XT\python3\imaris_extensions-main>pause
Press any key to continue . . .

**Comment by Noush-A** [comment]
Update; Seems like I just needed to change the directory in the .bat file to my Anaconda scripts directory. I was able to get the extension to work as a stand alone, but when I attempt to open in Imaris, a quick command prompt opens up and closes on its own quickly. Any help on how to get this to work in Imaris would be appreciated. Thansk.

**Comment by zivy** [comment]
Hello @Noush-A,

First, good to hear that you got the extensions working in standalone mode. That is the preferred approach as it does not require an imaris installation and license for the specific computer.

With respect to launching the extensions via the imaris interface, we have only done it with imaris 9.x.x and based on the error message you are working with imaris 10.1.1. 

Which version of Python does that imaris expect? In 9.x.x this was Python 3.7 which is then [specified in the environment.yml](https://github.com/niaid/imaris_extensions/blob/3a4f2a6611f393d659d5d809babfc4c532b08ea2/environment.yml#L6) file used to create the anaconda virtual environment. If the Python version expected by imaris is different this may cause a problem. Possibly share your settings with us? You can see my settings bellow (found under Imaris->CustomTools):
 
<img width="723" alt="Screen Shot 2024-06-28 at 2 02 28 PM" src="https://github.com/niaid/imaris_extensions/assets/338645/d06607d0-a9ca-4d3f-b0aa-25820ce8d8ae">

**Comment by Noush-A** [comment]
Thank you for your quick response, Zivy.
I am using Python 3.7 as it is what seems to be needed in Imaris under CustomTools. I actually switched back to 3.7 from 3.12 because I thought that might be the problem. 
![image](https://github.com/niaid/imaris_extensions/assets/174058466/418c2884-8638-4a69-96a8-e288fb3726b3)

**Comment by zivy** [comment]
Hello @Noush-A,

Based on your path the Python you are pointing to is not the version created when you installed the extensions (anaconda/miniconda virtual environment with all the required packages) and consequentially will not work. 

The path to the "Python 3.7 Application:" should look similar to what you see in my path. On windows it will be something like "...\miniconda3\envs\imaris\Python.exe".

**Comment by Noush-A** [comment]
Thanks Zivy, it's working now! Just to confirm, even if it is launched from Imaris, the extension still requires you to load a file, in other words, it doesn't take the file already open in Imaris as the input?

**Comment by zivy** [comment]
Hello @Noush-A,

Good to hear it is working. Yes, even when launched via the imaris GUI the extension functions independently from imaris, so you will need to open the file via the extension.

Our approach is that the extensions we develop are open source and play nicely with the commercial software but maintain independence from it and the need for commercial licenses.

**Comment by Noush-A** [comment]
Great, that makes sense.
Thanks again for your help.
